CREATED_STATE = "CREATED"
CANCELLED_STATE = "CANCELLED"
FULFILLED_STATE = "FULFILLED"
ORDER_STATES = (
    (CREATED_STATE, "Created"),
    (CANCELLED_STATE, "Cancelled"),
    (FULFILLED_STATE, "Fulfilled"),
)
