# Generated by Django 2.2.6 on 2022-09-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='fulfilled',
        ),
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('CREATED', 'Created'), ('CANCELLED', 'Cancelled'), ('FULFILLED', 'Fulfilled')], default='CREATED', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='state_change_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='quantity',
            field=models.PositiveIntegerField(default=1, editable=False, help_text='The number of actual tickets available upon creation'),
        ),
    ]
